name: habit_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter:
    sdk: flutter
  day_picker: ^2.3.0
  carousel_slider: ^5.0.0
  image_picker: ^0.8.7+4
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
