// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8y_Kp2U_xF07mDYm02F48sFlR-w5DVFI',
    appId: '1:970092773263:web:9a201bb2d1c50e58b095fa',
    messagingSenderId: '970092773263',
    projectId: 'habit-tracker-29053',
    authDomain: 'habit-tracker-29053.firebaseapp.com',
    storageBucket: 'habit-tracker-29053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Gh4f0eE29rXuP3pSl59TIkJlDF8USXY',
    appId: '1:970092773263:android:92236dfe5d21ac66b095fa',
    messagingSenderId: '970092773263',
    projectId: 'habit-tracker-29053',
    storageBucket: 'habit-tracker-29053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaOA_oj8M8NzpZs4ZE_MXi-kR1ONxgTQ',
    appId: '1:970092773263:ios:a9fc1d09b3e66577b095fa',
    messagingSenderId: '970092773263',
    projectId: 'habit-tracker-29053',
    storageBucket: 'habit-tracker-29053.appspot.com',
    iosBundleId: 'com.than.habitFrontend',
  );
}
